package(
    default_visibility = ["//src:__subpackages__"],
)

android_binary(
    name = "app",
    manifest = "AndroidManifest.xml",
    deps = [
        "//src/main/java/com/example/bazel:greeter_activity",
#                "@maven//:androidx_appcompat_appcompat",
#                "@maven//:com_google_android_material_material",
            ],
)