android_sdk_repository(
    name = "androidsdk",
    path = "c:/Users/TEMP.KENNETHMATHARI.001/AppData/Local/Android/Sdk",
    )

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "4.5"
RULES_JVM_EXTERNAL_SHA = "b17d7388feb9bfa7f2fa09031b32707df529f26c91ab9e5d909eb1676badd9a6"

#http_archive(
#    name = "robolectric",
#    urls = ["https://github.com/robolectric/robolectric-bazel/archive/4.9.2.tar.gz"],
#    sha256 = "7e007fcfdca7b7228cb4de72707e8b317026ea95000f963e91d5ae365be52d0d",
#    strip_prefix = "robolectric-bazel-4.9.2",
#)
#load("@robolectric//bazel:robolectric.bzl", "robolectric_repositories")
#robolectric_repositories()

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")
rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")
rules_jvm_external_setup()

load("@rules_jvm_external//:defs.bzl", "maven_install")
maven_install(
    name = "maven",
    artifacts = [
        "androidx.lifecycle:lifecycle-runtime:2.5.1",
        "androidx.cardview:cardview:1.0.0",
        "androidx.lifecycle:lifecycle-viewmodel:2.5.1",
        "androidx.lifecycle:lifecycle-livedata:2.5.1",
        "androidx.lifecycle:lifecycle-livedata-core:2.5.1",
#        "androidx.appcompat:appcompat:1.3.0",
#        "com.google.android.material:material:1.1.0-alpha06",
#        "junit:junit:4.13.2",
#        "androidx.test.ext:junit:1.1.5",
#        "androidx.test:core:1.5.0",
#        "org.robolectric:robolectric:4.9.2",
#        "androidx.test.espresso:espresso-core:3.5.0-alpha07",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
    #use_credentials_from_home_netrc_file = True,
    #maven_install_json = "//:maven_install.json",
    #use_credentials_from_home_netrc_file = True,
)

#load("@maven//:defs.bzl", "pinned_maven_install")
#pinned_maven_install()




